### ISSUE TITLE
Does not decrypt large files

### ISSUE THREAD

**Issue by mlangenberg** [marnix/synology-decrypt#23] opened 2018-01-01 17:48 UTC
I was unable to decrypt a large (4,09GB) file. 

If I remember correctly, I received the following error: "size doesn't fit in an int". I forgot the save the stack trace, but I do want to document the issue.

My solution was to use https://github.com/ewoutp/synology-decrypt-docker and use the tool provided by Synology within a Ubuntu docker container. Of course this adds a lot of overhead and give no insight in the encryption algorithm.

**Comment by anojht** [comment] 2020-01-21 19:18
I have been trying to tackle this one for a while now, and I need some assistance, @neepl @marnix any thoughts?

There must be something different that occurs when encrypting large files in the Synology cloud sync algorithm.

**Comment by marnix** [comment] 2020-02-03 19:10
@anojht Can you please show what error message / Python stack trace you get, with this 'size doesn't fit in an int' message?  Where does it occur?

Also, it might help to know which exact version of Python you're using?

Thanks in advance!

**Comment by anojht** [comment] 2020-02-04 20:08
```
2019-05-13 20:09:02,952 INFO syndecrypt.files decrypting "/Users/kyle/Downloads/Borat Cultural Learnings of America for Make Benefit Glorious Nation of Kazakhstan.mkv" to "/Users/kyle/Documents/Borat Cultural Learnings of America for Make Benefit Glorious Nation of Kazakhstan.mkv"
2019-05-13 20:09:35,267 ERROR syndecrypt.files decryption failed, exception occurred: <class 'OverflowError'>: size does not fit in an int
2019-05-13 20:09:35,270 ERROR synology_logger size does not fit in an int
Traceback (most recent call last):
  File "Synology.py", line 199, in validate
    run_tool()
  File "Synology.py", line 302, in run_tool
    __main__.main(['-p', pword, out, input])
  File "/Users/kyle/bin/synology-cloud-sync-decrypt-tool-master/syndecrypt/__main__.py", line 96, in main
    files.decrypt_file(ff, os.path.join(output_dir, fp), password=password, private_key=private_key, public_key=public_key)
  File "/Users/kyle/bin/synology-cloud-sync-decrypt-tool-master/syndecrypt/files.py", line 28, in decrypt_file
    core.decrypt_stream(instream, outstream, password=password, private_key=private_key, public_key=public_key)
  File "/Users/kyle/bin/synology-cloud-sync-decrypt-tool-master/syndecrypt/core.py", line 240, in decrypt_stream
    decrypted_data = decryptor_update(decryptor, bytes(data))
  File "/Users/kyle/bin/synology-cloud-sync-decrypt-tool-master/syndecrypt/core.py", line 94, in decryptor_update
    return strip_PKCS7_padding(decryptor.decrypt(ciphertext))
  File "/Users/kyle/syndecrypt-venv/lib/python3.7/site-packages/Crypto/Cipher/blockalgo.py", line 295, in decrypt
    return self._cipher.decrypt(ciphertext)
OverflowError: size does not fit in an int
```

@marnix I am running python 3.7, thanks for your help! 😄

**Comment by marnix** [comment] 2020-02-08 14:08
Not sure if this is the cause, and I'll try to reproduce this issue locally, but based on that stack trace you seem to be using `pycrypto` while my intention was to use `pycryptodome` (see pull request #27).

However, having both installed gives unpredictable results, it seems, see e.g. https://pycryptodome.readthedocs.io/en/latest/src/installation.html.

Therefore in #31 which I just merged, I switched the source code to use `pycryptodomex` and the corresponding top-level package `Cryptodome` (instead of `Crypto`).

Could you try again with the most recent master, so commit b32fda7e?  Also, if that doesn't fix the issue, can you please again provide the stack trace, and let me know which exact version of pycryptodomex you are using?

Thanks!

**Comment by anojht** [comment] 2020-02-09 01:02
Huge thanks to your hard work! The changes committed worked for me. I can decrypt a 4GB MKV no problem and other file types work for V3.0 changes. I did however have to change something for password decryption to work for me, please see my version of [core.py](https://github.com/anojht/synology-cloud-sync-decrypt-tool/commit/965c222c27b1b9076b7026f84bafd1703d67c2d6).

**Comment by marnix** [comment] 2020-02-11 18:55
Doing a diff between the current master core.py, so from commit 76d9614 (link: https://raw.githubusercontent.com/marnix/synology-decrypt/76d9614ec428e38692a9acd56d3f58e7aec8f68d/syndecrypt/core.py) and your version (link: https://raw.githubusercontent.com/anojht/synology-cloud-sync-decrypt-tool/965c222c27b1b9076b7026f84bafd1703d67c2d6/syndecrypt/core.py) shows that they are basically identical:

```
$ diff -w a.py b.py
2a3
> import codecs
36a38,41
>         try:
>                 pwd = pwd.encode()
>         except AttributeError:
>                 pass
88d92
< 
91a96,99
>         try:
>                 data = data.encode()
>         except AttributeError:
>                 pass
174c182
< def decrypt_stream(instream, outstream, password=None, private_key=None):
---
> def decrypt_stream(instream, outstream, password=None, private_key=None, public_key=None):
$ 
```

So could you perhaps try again with current master, and if you see something wrong, open a new issue?

**Comment by marnix** [comment] 2020-02-11 18:57
I'm going to close this issue, since as far as I can see, and hear from you, this 'large file' issue has been resolved (as has the 'invalid padding byte' error).  Again, thanks for the report and the details!

**Closed as completed by marnix** 2020-02-11 18:57 UTC
